server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 80KB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/foodie-shop-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 2
      pool-name: HikariCP
mybatis-plus:
  type-aliases-package: com.moxuan.pojo
  mapper-locations: classpath:mapper/*.xml
