############################################################
#
# 配置文件对应的版本
#
############################################################
spring:
  application:
    name: foodie
  profiles:
    active: @profileActive@
  messages:
    encoding: UTF-8
    basename: i18n/messages
    cache-duration: 7200s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: 80KB
