############################################################
#
# 配置文件对应的版本
#
############################################################
spring:
  application:
    name: foodie
  profiles:
    active: @profileActive@
  messages:
    encoding: UTF-8
    basename: i18n/messages
    cache-duration: 7200s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
############################################################
#
# web访问端口号  约定：8089
#
############################################################
server:
  port: 8089
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: 80KB




